/**
 * End-to-end smoke test for the genomics API against a running server.
 *
 * Exercises the paths that unit tests cannot: consent enforcement across HTTP,
 * multipart upload, persistence, and the audit trail.
 *
 *   npm run dev            # in one terminal
 *   npx tsx scripts/smoke-genomics-api.ts [baseUrl]
 */
const BASE = (process.argv[2] || 'http://localhost:5000').trim().replace(/\/+$/, '');

// The WHATWG fetch spec maintains a blocked-port list, and Node's fetch enforces
// it. A server listening on one of these is unreachable from this script and the
// only symptom is "bad port", which does not point at the cause.
const BLOCKED_PORTS = new Set([
  1719, 1720, 1723, 2049, 3659, 4045, 5060, 5061, 6000, 6566, 6665, 6666, 6667,
  6668, 6669, 6697, 10080,
]);
const parsedPort = Number.parseInt(new URL(BASE).port, 10);
if (BLOCKED_PORTS.has(parsedPort)) {
  console.error(
    `Port ${parsedPort} is on the fetch blocked-port list and cannot be reached ` +
    'by this script. Start the server on a different port.'
  );
  process.exit(1);
}

let cookie = '';
let passed = 0;
const failures: string[] = [];

async function call(
  method: string,
  path: string,
  body?: any,
  form?: FormData
): Promise<{ status: number; json: any }> {
  const headers: Record<string, string> = {};
  if (cookie) headers.Cookie = cookie;
  if (body) headers['Content-Type'] = 'application/json';

  const res = await fetch(`${BASE}${path}`, {
    method,
    headers,
    body: form ? (form as any) : body ? JSON.stringify(body) : undefined,
  });

  const setCookie = res.headers.get('set-cookie');
  if (setCookie) cookie = setCookie.split(';')[0];

  let json: any = null;
  try {
    json = await res.json();
  } catch {
    /* non-JSON responses are reported via status alone */
  }
  return { status: res.status, json };
}

function check(name: string, condition: boolean, detail?: string): void {
  if (condition) {
    passed++;
    console.log(`  PASS  ${name}`);
  } else {
    failures.push(`${name}${detail ? ` — ${detail}` : ''}`);
    console.log(`  FAIL  ${name}${detail ? ` — ${detail}` : ''}`);
  }
}

const GENOTYPE_FILE = [
  '# This data file generated by 23andMe',
  '# build 37',
  '#rsid\tchromosome\tposition\tgenotype',
  // melanoma synthetic panel variants
  'rs16891982\t5\t33951693\tCC',
  'rs12913832\t15\t28365618\tGG',
  'rs1805007\t16\t89986117\tTT',
  'rs1805008\t16\t89986144\tTT',
  'rs1393350\t11\t89011046\tAA',
  'rs910873\t20\t33171772\tAA',
  'rs6059655\t20\t33218090\tAA',
  'rs2218220\t11\t69516148\tTT',
  'rs7412746\t22\t39351666\tCC',
  'rs4636294\t9\t21802635\tAA',
  // actionable panel variants
  'rs80357906\t17\t41244000\tAG',
  'rs80359550\t13\t32914438\tCC',
  'rs28897743\t13\t32912299\tAA',
].join('\n');

async function main() {
  console.log(`Genomics API smoke test against ${BASE}\n`);

  // --- transparency endpoints, no auth ---
  const panels = await call('GET', '/api/genomics/panels');
  check('GET /panels returns 200', panels.status === 200, `got ${panels.status}`);
  check(
    'synthetic panels are marked not-clinical',
    panels.json?.polygenicPanels?.some((p: any) => p.provenance === 'synthetic' && p.clinicalUseAllowed === false)
  );

  const transfer = await call('GET', '/api/genomics/transferability');
  check('GET /transferability returns 200', transfer.status === 200);
  const african = transfer.json?.groups?.find((g: any) => g.group === 'african');
  check('African group withholds percentile', african?.percentileReported === false);

  // --- register + login ---
  // Usernames are capped at 20 chars by the registration schema, so the
  // uniqueness suffix has to be short.
  const suffix = Date.now().toString(36).slice(-6);
  const username = `geno_${suffix}`;
  const reg = await call('POST', '/api/auth/register', {
    username,
    password: 'GenoProbe123',
    role: 'patient',
    fullName: 'Genomics Probe',
    email: `${username}@example.com`,
  });
  check('registration succeeds', reg.status === 200, JSON.stringify(reg.json));
  const patientId = reg.json?.id;
  if (!patientId) {
    console.error('\nCannot continue without a patient id.');
    process.exit(1);
  }

  const login = await call('POST', '/api/auth/login', { username, password: 'GenoProbe123' });
  check('login succeeds', login.status === 200, JSON.stringify(login.json));

  const me = await call('GET', '/api/auth/me');
  if (me.status !== 200) {
    console.error(
      '\nSession did not persist across requests, so the authenticated portion ' +
      'cannot run. This is a pre-existing session issue, not a genomics one.'
    );
    process.exit(failures.length ? 1 : 0);
  }

  // --- consent is required before upload ---
  const form = new FormData();
  form.append('patientId', String(patientId));
  form.append('selfReportedAncestry', 'European');
  form.append('genotypeFile', new Blob([GENOTYPE_FILE], { type: 'text/plain' }), 'genome.txt');

  // Self-access is permitted without an explicit grant, so upload should work.
  const upload = await call('POST', '/api/genomics/profile/upload', undefined, form);
  check('upload succeeds for self', upload.status === 200, JSON.stringify(upload.json));
  check('only panel-relevant variants stored', upload.json?.variantsStored === 13,
    `stored ${upload.json?.variantsStored}`);
  check('build detected', upload.json?.genomeBuild === 'GRCh37');

  // --- risk computation ---
  const risk = await call('POST', `/api/genomics/risk/${patientId}`, { condition: 'melanoma' });
  check('risk computation returns 200', risk.status === 200, JSON.stringify(risk.json).slice(0, 300));
  check('synthetic data blocks clinical use', risk.json?.clinicalUseAllowed === false);
  check('clinician review always required', risk.json?.requiresClinicianReview === true);
  check('polygenic coverage reported', typeof risk.json?.polygenic?.coveragePct === 'number');
  check('ancestry block present', risk.json?.ancestry?.group === 'european');
  check('actionable finding surfaced', (risk.json?.actionableVariants?.findings?.length ?? 0) >= 1);
  check('band raised to high by pathogenic finding', risk.json?.band === 'high',
    `band was ${risk.json?.band}`);
  check('synthetic warning leads caveats', /SYNTHETIC/i.test(risk.json?.caveats?.[0] ?? ''));

  // --- audit trail ---
  const log = await call('GET', `/api/genomics/access-log/${patientId}`);
  check('access log readable by patient', log.status === 200);
  check('upload and compute_risk both logged',
    ['upload', 'compute_risk'].every((a: string) =>
      log.json?.entries?.some((e: any) => e.action === a)));

  // --- consent revocation is recorded ---
  const revoke = await call('POST', '/api/genomics/consent', {
    patientId, scope: 'research', granted: false,
  });
  check('consent revocation recorded', revoke.status === 200 &&
    revoke.json?.consents?.research?.granted === false);

  // --- deletion keeps the audit trail ---
  const del = await call('DELETE', `/api/genomics/profile/${patientId}`);
  check('genomic data deletable', del.status === 200, JSON.stringify(del.json));
  const logAfter = await call('GET', `/api/genomics/access-log/${patientId}`);
  check('access log survives deletion', (logAfter.json?.entries?.length ?? 0) > 0);

  console.log(`\n${passed} passed, ${failures.length} failed`);
  if (failures.length) {
    console.error('\nFAILURES:');
    for (const f of failures) console.error(`  - ${f}`);
    process.exit(1);
  }
}

main().catch((error) => {
  console.error('Smoke test crashed:', error);
  process.exit(1);
});
