/**
 * Tests for the genomics risk engine.
 *
 * Only the pure modules are exercised here — parsers, scoring, ancestry
 * calibration, actionable screening and fusion. They have no database
 * dependency, so this runs anywhere with `npm run test:genomics`.
 *
 * The assertions concentrate on the failure modes that would be invisible in
 * production: a missing genotype silently counted as zero risk alleles, a
 * percentile released for an ancestry it does not describe, a reassuring
 * polygenic score talking down a flagged lesion, synthetic data escaping into a
 * clinical field.
 */
import assert from 'node:assert/strict';

import { parseConsumerRawFile, parseVcf, parseGenotypeFile, GenotypeParseError } from '../server/genomics/parsers';
import { dosage, computePrs, parsePgsScoringFile, type ScoringPanel } from '../server/genomics/prs';
import { getTransferability, percentileInterval, resolveAncestryGroup } from '../server/genomics/ancestry';
import { screenActionableVariants, type ActionablePanel } from '../server/genomics/actionable-variants';
import { fuseRisk } from '../server/genomics/fusion';

let passed = 0;
const failures: string[] = [];

function test(name: string, fn: () => void): void {
  try {
    fn();
    passed++;
  } catch (error) {
    failures.push(`${name}\n    ${error instanceof Error ? error.message : String(error)}`);
  }
}

// ---------------------------------------------------------------------------
// Parsers
// ---------------------------------------------------------------------------

const CONSUMER_FILE = [
  '# This data file generated by 23andMe at: Mon Jan 01 00:00:00 2024',
  '# build 37',
  '#rsid\tchromosome\tposition\tgenotype',
  'rs1805007\t16\t89986117\tCT',
  'rs12913832\t15\t28365618\tAG',
  'rs16891982\t5\t33951693\t--',
  'rs1393350\t11\t89011046\tGA',
].join('\n');

test('consumer parser reads genotypes and detects build', () => {
  const result = parseConsumerRawFile(CONSUMER_FILE);
  assert.equal(result.source, '23andme');
  assert.equal(result.genomeBuild, 'GRCh37');
  assert.equal(result.genotypes.length, 4);
});

test('consumer parser sorts alleles so GA and AG are equal', () => {
  const result = parseConsumerRawFile(CONSUMER_FILE);
  const rs1393350 = result.genotypes.find((g) => g.rsid === 'rs1393350');
  assert.equal(rs1393350?.genotype, 'AG', 'GA should normalise to AG');
});

test('consumer parser normalises no-calls to --', () => {
  const result = parseConsumerRawFile(CONSUMER_FILE);
  assert.equal(result.genotypes.find((g) => g.rsid === 'rs16891982')?.genotype, '--');
});

test('consumer parser warns when build is undeclared', () => {
  const noBuild = '#rsid\tchromosome\tposition\tgenotype\nrs1805007\t16\t89986117\tCT';
  const result = parseConsumerRawFile(noBuild);
  assert.equal(result.genomeBuild, null);
  assert.ok(result.warnings.some((w) => /build/i.test(w)), 'should warn about missing build');
});

test('consumer parser rejects a file with no genotype rows', () => {
  assert.throws(() => parseConsumerRawFile('# only a header\n'), GenotypeParseError);
});

test('consumer parser keeps the first call for a duplicated rsid', () => {
  const dup = [
    '# build 37',
    'rs1805007\t16\t89986117\tCT',
    'rs1805007\t16\t89986117\tTT',
  ].join('\n');
  const result = parseConsumerRawFile(dup);
  assert.equal(result.genotypes.length, 1);
  assert.equal(result.genotypes[0].genotype, 'CT');
  assert.equal(result.skipped, 1);
});

const VCF_FILE = [
  '##fileformat=VCFv4.2',
  '##reference=GRCh37',
  '#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE1',
  '16\t89986117\trs1805007\tC\tT\t50\tPASS\t.\tGT\t0/1',
  '15\t28365618\trs12913832\tA\tG\t50\tPASS\t.\tGT\t1/1',
  '11\t89011046\trs1393350\tG\tA\t50\tPASS\t.\tGT\t./.',
].join('\n');

test('vcf parser maps GT fields to diploid calls', () => {
  const result = parseVcf(VCF_FILE);
  assert.equal(result.source, 'vcf');
  assert.equal(result.genomeBuild, 'GRCh37');
  const byRsid = new Map(result.genotypes.map((g) => [g.rsid, g.genotype]));
  assert.equal(byRsid.get('rs1805007'), 'CT', 'het 0/1 should be REF+ALT');
  assert.equal(byRsid.get('rs12913832'), 'GG', 'hom 1/1 should be ALT+ALT');
  assert.equal(byRsid.get('rs1393350'), '--', 'missing ./. should be a no-call');
});

test('vcf parser refuses multi-sample files rather than guessing a column', () => {
  const multi = VCF_FILE.replace('\tSAMPLE1', '\tSAMPLE1\tSAMPLE2');
  assert.throws(() => parseVcf(multi), /single-sample/i);
});

test('format dispatch picks the parser from content, not filename', () => {
  assert.equal(parseGenotypeFile(VCF_FILE).source, 'vcf');
  assert.equal(parseGenotypeFile(CONSUMER_FILE).source, '23andme');
});

// ---------------------------------------------------------------------------
// Dosage and PRS
// ---------------------------------------------------------------------------

test('dosage counts effect allele copies', () => {
  assert.equal(dosage('CT', 'T'), 1);
  assert.equal(dosage('TT', 'T'), 2);
  assert.equal(dosage('CC', 'T'), 0);
});

test('dosage returns null for a no-call rather than zero', () => {
  // Treating a missing genotype as 0 copies silently biases every score down.
  assert.equal(dosage('--', 'T'), null);
  assert.equal(dosage('', 'T'), null);
});

const PANEL: ScoringPanel = {
  id: 'TEST-PANEL',
  condition: 'melanoma',
  provenance: 'pgs_catalog',
  pgsId: 'PGS999999',
  genomeBuild: 'GRCh37',
  discoveryAncestry: 'European',
  citation: 'test',
  variants: [
    { rsid: 'rs1', effectAllele: 'T', otherAllele: 'C', weight: 0.5 },
    { rsid: 'rs2', effectAllele: 'G', otherAllele: 'A', weight: 0.25 },
    { rsid: 'rs3', effectAllele: 'A', otherAllele: 'G', weight: 1.0 },
    { rsid: 'rs4', effectAllele: 'C', otherAllele: 'T', weight: 0.1 },
    { rsid: 'rs5', effectAllele: 'T', otherAllele: 'A', weight: 0.2 },
  ],
};

test('prs sums weight x dosage over genotyped variants', () => {
  const genotypes = new Map([
    ['rs1', 'TT'],  // 2 x 0.5  = 1.0
    ['rs2', 'AG'],  // 1 x 0.25 = 0.25
    ['rs3', 'GG'],  // 0 x 1.0  = 0
    ['rs4', 'CC'],  // 2 x 0.1  = 0.2
    ['rs5', 'AT'],  // 1 x 0.2  = 0.2
  ]);
  const result = computePrs(PANEL, genotypes, { mean: 1.0, sd: 0.5 });
  assert.ok(Math.abs(result.rawScore - 1.65) < 1e-9, `expected 1.65, got ${result.rawScore}`);
  assert.equal(result.coveragePct, 100);
  assert.equal(result.matchedVariants, 5);
});

test('prs withholds a percentile below the coverage floor', () => {
  const genotypes = new Map([['rs1', 'TT'], ['rs2', 'AG']]); // 40% coverage
  const result = computePrs(PANEL, genotypes, { mean: 1.0, sd: 0.5 });
  assert.equal(result.coveragePct, 40);
  assert.equal(result.percentile, null);
  assert.match(result.percentileWithheldReason ?? '', /genotyped/i);
});

test('prs withholds a percentile when no reference distribution exists', () => {
  const genotypes = new Map(PANEL.variants.map((v) => [v.rsid, `${v.effectAllele}${v.effectAllele}`]));
  const result = computePrs(PANEL, genotypes, null);
  assert.equal(result.percentile, null);
  assert.match(result.percentileWithheldReason ?? '', /reference distribution/i);
});

test('prs excludes no-calls from coverage instead of scoring them as zero', () => {
  const withNoCall = new Map([
    ['rs1', 'TT'], ['rs2', 'AG'], ['rs3', '--'], ['rs4', 'CC'], ['rs5', 'AT'],
  ]);
  const result = computePrs(PANEL, withNoCall, { mean: 1.0, sd: 0.5 });
  assert.equal(result.matchedVariants, 4, 'no-call must not count as genotyped');
  assert.equal(result.coveragePct, 80);
});

test('prs refuses a percentile when genome builds disagree', () => {
  const genotypes = new Map(PANEL.variants.map((v) => [v.rsid, `${v.effectAllele}${v.effectAllele}`]));
  const result = computePrs(PANEL, genotypes, { mean: 1.0, sd: 0.5 }, 'GRCh38');
  assert.equal(result.percentile, null, 'GRCh37 panel vs GRCh38 genotypes must not score');
  assert.match(result.percentileWithheldReason ?? '', /build mismatch/i);
  assert.ok(result.warnings.some((w) => /build mismatch/i.test(w)));
});

test('prs scores normally when builds match', () => {
  const genotypes = new Map(PANEL.variants.map((v) => [v.rsid, `${v.effectAllele}${v.effectAllele}`]));
  const result = computePrs(PANEL, genotypes, { mean: 1.0, sd: 0.5 }, 'GRCh37');
  assert.notEqual(result.percentile, null);
});

test('prs warns when the genotype build is undeclared', () => {
  const genotypes = new Map(PANEL.variants.map((v) => [v.rsid, `${v.effectAllele}${v.effectAllele}`]));
  const result = computePrs(PANEL, genotypes, { mean: 1.0, sd: 0.5 }, null);
  assert.ok(result.warnings.some((w) => /did not declare a reference build/i.test(w)));
});

test('prs flags synthetic panels in its warnings', () => {
  const synthetic: ScoringPanel = { ...PANEL, provenance: 'synthetic' };
  const genotypes = new Map(PANEL.variants.map((v) => [v.rsid, `${v.effectAllele}${v.effectAllele}`]));
  const result = computePrs(synthetic, genotypes, { mean: 1, sd: 0.5 });
  assert.ok(result.warnings.some((w) => /synthetic/i.test(w)));
});

test('pgs catalog scoring file parses metadata and variants', () => {
  const file = [
    '#pgs_id=PGS000123',
    '#genome_build=GRCh37',
    'rsID\teffect_allele\tother_allele\teffect_weight',
    'rs100\tA\tG\t0.15',
    'rs200\tT\tC\t-0.08',
  ].join('\n');
  const panel = parsePgsScoringFile(file, 'melanoma');
  assert.equal(panel.pgsId, 'PGS000123');
  assert.equal(panel.genomeBuild, 'GRCh37');
  assert.equal(panel.provenance, 'pgs_catalog');
  assert.equal(panel.variants.length, 2);
  assert.equal(panel.variants[1].weight, -0.08);
});

// ---------------------------------------------------------------------------
// Ancestry transferability
// ---------------------------------------------------------------------------

test('unknown ancestry does not default to European', () => {
  const transfer = getTransferability(null);
  assert.equal(transfer.group, 'unknown');
  assert.equal(transfer.percentileReportable, false, 'must not report a percentile');
  assert.ok(transfer.factor < 1.0);
});

test('African ancestry withholds the percentile', () => {
  const transfer = getTransferability('African');
  assert.equal(transfer.group, 'african');
  assert.equal(transfer.percentileReportable, false);
  assert.ok(transfer.factor <= 0.3, 'should reflect substantially reduced accuracy');
});

test('European ancestry reports a percentile at full factor', () => {
  const transfer = getTransferability('European');
  assert.equal(transfer.percentileReportable, true);
  assert.equal(transfer.factor, 1.0);
});

test('ancestry aliases resolve free text', () => {
  assert.equal(resolveAncestryGroup('Black South African'), 'african');
  assert.equal(resolveAncestryGroup('Han Chinese'), 'east_asian');
  assert.equal(resolveAncestryGroup('  '), null);
  assert.equal(resolveAncestryGroup('Klingon'), null, 'unrecognised must not be guessed');
});

test('lower transferability produces a visibly wider interval', () => {
  const narrow = percentileInterval(50, 1.0);
  const wide = percentileInterval(50, 0.25);
  assert.ok(wide.widthPct > narrow.widthPct * 2, 'poor transfer must widen the band');
});

// ---------------------------------------------------------------------------
// Actionable variants
// ---------------------------------------------------------------------------

const ACTIONABLE: ActionablePanel = {
  source: 'test',
  version: 'v1',
  synthetic: false,
  variants: [
    { rsid: 'rsP1', gene: 'BRCA1', riskAllele: 'A', classification: 'pathogenic', condition: 'HBOC', clinvarId: '1', inheritance: 'AD' },
    { rsid: 'rsP2', gene: 'BRCA2', riskAllele: 'T', classification: 'pathogenic', condition: 'HBOC', clinvarId: '2', inheritance: 'AD' },
    { rsid: 'rsV1', gene: 'BRCA2', riskAllele: 'G', classification: 'uncertain_significance', condition: 'HBOC', clinvarId: '3', inheritance: 'AD' },
  ],
};

test('actionable screening reports a pathogenic carrier', () => {
  const result = screenActionableVariants(new Map([['rsP1', 'AG'], ['rsP2', 'CC'], ['rsV1', 'AA']]), ACTIONABLE);
  assert.equal(result.findings.length, 1);
  assert.equal(result.findings[0].gene, 'BRCA1');
  assert.equal(result.findings[0].copies, 1);
});

test('variants of uncertain significance are not reported as findings', () => {
  const result = screenActionableVariants(new Map([['rsP1', 'GG'], ['rsP2', 'CC'], ['rsV1', 'GG']]), ACTIONABLE);
  assert.equal(result.findings.length, 0, 'VUS must not surface as a finding');
});

test('un-assayed positions are counted as unknown, not negative', () => {
  const result = screenActionableVariants(new Map([['rsP1', 'GG']]), ACTIONABLE);
  assert.equal(result.notAssayed.length, 2);
  assert.equal(result.assayedNegative, 1);
  assert.ok(result.caveats.some((c) => /not negative/i.test(c)));
});

test('no installed panel reports "not screened", never a clean result', () => {
  const result = screenActionableVariants(new Map([['rsP1', 'AA']]), null);
  assert.equal(result.screened, false);
  assert.equal(result.findings.length, 0);
  assert.ok(result.caveats.some((c) => /not a negative result/i.test(c)));
});

test('a clean screen still warns that coverage is partial', () => {
  const all = new Map([['rsP1', 'GG'], ['rsP2', 'CC'], ['rsV1', 'AA']]);
  const result = screenActionableVariants(all, ACTIONABLE);
  assert.equal(result.findings.length, 0);
  assert.ok(result.caveats.some((c) => /does NOT rule out/i.test(c)));
});

// ---------------------------------------------------------------------------
// Fusion
// ---------------------------------------------------------------------------

function prsAt(percentile: number | null, provenance: 'pgs_catalog' | 'synthetic' = 'pgs_catalog') {
  return {
    panelId: 'TEST', condition: 'melanoma', provenance,
    rawScore: 1, matchedVariants: 5, panelSize: 5, coveragePct: 100,
    percentile, percentileWithheldReason: percentile === null ? 'withheld' : null,
    warnings: [],
  };
}

const FLAGGED: Parameters<typeof fuseRisk>[0]['imaging'] = {
  scanId: 1, flagged: true, confidence: 95, riskLevel: 'high',
};
const CLEAR: Parameters<typeof fuseRisk>[0]['imaging'] = {
  scanId: 2, flagged: false, confidence: 90, riskLevel: 'low',
};

test('a flagged high-risk scan sets the band high', () => {
  const result = fuseRisk({ condition: 'melanoma', imaging: FLAGGED });
  assert.equal(result.band, 'high');
});

test('a low polygenic score cannot lower a flagged lesion', () => {
  const result = fuseRisk({
    condition: 'melanoma',
    imaging: FLAGGED,
    prs: prsAt(5),
    transferability: getTransferability('European'),
  });
  assert.equal(result.band, 'high', 'a reassuring PRS must never talk down imaging');
});

test('a high polygenic score raises a clear scan to moderate', () => {
  const result = fuseRisk({
    condition: 'melanoma',
    imaging: CLEAR,
    prs: prsAt(95),
    transferability: getTransferability('European'),
  });
  assert.equal(result.band, 'moderate');
});

test('an untransferable polygenic score is excluded, not down-weighted', () => {
  const result = fuseRisk({
    condition: 'melanoma',
    imaging: CLEAR,
    prs: prsAt(99),
    transferability: getTransferability('African'),
  });
  assert.equal(result.band, 'low', 'a score that does not transfer must not move the band');
  const prsContribution = result.contributions.find((c) => c.source === 'polygenic_score');
  assert.equal(prsContribution?.effect, 'excluded');
});

test('a pathogenic finding raises the band to high on its own', () => {
  const result = fuseRisk({
    condition: 'melanoma',
    imaging: CLEAR,
    actionable: screenActionableVariants(new Map([['rsP1', 'AA'], ['rsP2', 'CC'], ['rsV1', 'AA']]), ACTIONABLE),
  });
  assert.equal(result.band, 'high');
});

test('no inputs yields indeterminate, explicitly not low', () => {
  const result = fuseRisk({ condition: 'melanoma' });
  assert.equal(result.band, 'indeterminate');
  assert.ok(result.caveats.some((c) => /not a low-risk result/i.test(c)));
  assert.ok(result.missingInputs.length >= 3);
});

test('synthetic input blocks clinical use and leads the caveats', () => {
  const result = fuseRisk({
    condition: 'melanoma',
    imaging: CLEAR,
    prs: prsAt(95, 'synthetic'),
    transferability: getTransferability('European'),
  });
  assert.equal(result.containsSyntheticData, true);
  assert.match(result.caveats[0], /SYNTHETIC/);
});

test('every fused result demands clinician review', () => {
  for (const input of [
    { condition: 'melanoma', imaging: FLAGGED },
    { condition: 'melanoma', imaging: CLEAR },
    { condition: 'melanoma' },
  ]) {
    assert.equal(fuseRisk(input).requiresClinicianReview, true);
  }
});

test('missing imaging is named in the output', () => {
  const result = fuseRisk({
    condition: 'melanoma',
    prs: prsAt(95),
    transferability: getTransferability('European'),
  });
  assert.ok(result.missingInputs.some((m) => /imaging/i.test(m)));
});

// ---------------------------------------------------------------------------

console.log(`\n${passed} passed, ${failures.length} failed`);
if (failures.length) {
  console.error('\nFAILURES:');
  for (const failure of failures) console.error(`  - ${failure}`);
  process.exit(1);
}
