import { useState } from 'react';
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Checkbox } from "@/components/ui/checkbox";
import { useMutation } from "@tanstack/react-query";
import { useToast } from "@/hooks/use-toast";
import { 
  Upload, 
  Wind, 
  Eye, 
  AlertTriangle, 
  CheckCircle, 
  Activity,
  Target,
  Circle,
  Zap
} from "lucide-react";

/**
 * What this component can honestly show.
 *
 * Removed from this interface, because nothing produced them: nodule size,
 * location, density, margins, calcification and cavitation; a Lung-RADS score;
 * CEA/CYFRA 21-1/NSE/proGRP biomarkers; and TNM staging. All were generated by
 * Math.random() in the browser. Lung-RADS requires a measured nodule size and
 * type, the biomarkers are blood tests, and staging needs a full workup — a
 * binary chest-image classifier yields none of them.
 *
 * `clinicalRiskScore` is kept: it is a transparent sum over the answers the user
 * gave in the questionnaire, not a model output, and it is labelled as such.
 */
interface LungAnalysisResult {
  /** From the model: did the classifier flag this image. */
  flaggedByModel: boolean;
  /** Classifier confidence, 0-100. */
  confidence: number;
  /** From the questionnaire only. Not derived from the image. */
  clinicalRiskLevel: 'low' | 'intermediate' | 'high';
  clinicalRiskFactors: string[];
  recommendations: string[];
  requiresHumanReview: boolean;
}

interface PatientRiskFactors {
  smokingHistory: 'never' | 'former' | 'current';
  packYears: number;
  age: number;
  occupationalExposure: string[];
  familyHistory: boolean;
  previousCancer: boolean;
  chronicLungDisease: boolean;
}

export default function LungCancerAnalyzer() {
  const { toast } = useToast();
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [previewUrl, setPreviewUrl] = useState<string>("");
  const [analysisResult, setAnalysisResult] = useState<LungAnalysisResult | null>(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [analysisProgress, setAnalysisProgress] = useState(0);
  const [activeTab, setActiveTab] = useState('upload');
  const [riskFactors, setRiskFactors] = useState<PatientRiskFactors>({
    smokingHistory: 'never',
    packYears: 0,
    age: 50,
    occupationalExposure: [],
    familyHistory: false,
    previousCancer: false,
    chronicLungDisease: false
  });

  const lungAnalysisMutation = useMutation({
    mutationFn: async (data: { file: File; riskFactors: PatientRiskFactors }) => {
      const formData = new FormData();
      formData.append('image', data.file);
      formData.append('scanType', 'lung');
      formData.append('riskFactors', JSON.stringify(data.riskFactors));
      
      const response = await fetch('/api/scan/upload', {
        method: 'POST',
        body: formData
      });
      
      const payload = await response.json().catch(() => null);

      // 422 = the image itself was refused (wrong subject, blank, blurred).
      if (response.status === 422) {
        const reasons = Array.isArray(payload?.reasons) ? payload.reasons.join(' ') : '';
        throw new Error(`${payload?.message ?? 'Image rejected.'} ${reasons}`.trim());
      }

      // 503 = no validated model could run. Not a negative result.
      if (response.status === 503) {
        throw new Error(
          payload?.message ||
          'No validated model could analyse this scan. This is not a negative result.'
        );
      }

      if (!response.ok) {
        throw new Error(payload?.error || 'Lung analysis failed');
      }

      return payload;
    },
    onSuccess: (data) => {
      const result = buildLungResult(data.analysis, riskFactors);
      setAnalysisResult(result);
      setIsAnalyzing(false);
      setAnalysisProgress(100);
      setActiveTab('results');

      toast({
        title: "Analysis complete",
        description: result.flaggedByModel
          ? `Model flagged this scan at ${result.confidence.toFixed(1)}% confidence. Requires radiologist review.`
          : `Model did not flag this scan (${result.confidence.toFixed(1)}% confidence). Requires radiologist review.`,
      });
    },
    onError: (error: any) => {
      setIsAnalyzing(false);
      setAnalysisProgress(0);
      setAnalysisResult(null);
      toast({
        title: "No result produced",
        description: error.message || "Analysis could not be completed.",
        variant: "destructive",
      });
    }
  });

  /**
   * Builds the view model from the model output plus the questionnaire.
   *
   * The two are kept separate on purpose. `flaggedByModel` comes only from the
   * classifier; `clinicalRiskLevel` comes only from the answers the user gave.
   * The previous version mixed them and then added randomness on top —
   * `hasNodule` was `baseResult.hasCancer || confidence < 75 || Math.random() > 0.6`,
   * so the image classifier's actual answer could be overridden by a dice roll.
   */
  const buildLungResult = (baseResult: any, factors: PatientRiskFactors): LungAnalysisResult => {
    const confidence = parseFloat(baseResult.confidence) || 0;
    const flaggedByModel = baseResult.hasCancer === true || baseResult.status === 'abnormal';

    // Transparent questionnaire scoring. Every term is visible to the user below.
    const contributions: string[] = [];
    let riskScore = 0;
    if (factors.smokingHistory === 'current') { riskScore += 3; contributions.push('Current smoker (+3)'); }
    else if (factors.smokingHistory === 'former') { riskScore += 2; contributions.push('Former smoker (+2)'); }
    if (factors.packYears > 30) { riskScore += 2; contributions.push(`${factors.packYears} pack-years (+2)`); }
    if (factors.age > 65) { riskScore += 1; contributions.push(`Age ${factors.age} (+1)`); }
    if (factors.familyHistory) { riskScore += 1; contributions.push('Family history (+1)'); }
    if (factors.occupationalExposure.length > 0) {
      riskScore += 1;
      contributions.push(`Occupational exposure: ${factors.occupationalExposure.join(', ')} (+1)`);
    }

    const clinicalRiskLevel: 'low' | 'intermediate' | 'high' =
      riskScore >= 5 ? 'high' : riskScore >= 3 ? 'intermediate' : 'low';

    return {
      flaggedByModel,
      confidence,
      clinicalRiskLevel,
      clinicalRiskFactors: contributions.length ? contributions : ['No risk factors recorded'],
      // Prefer the server's recommendations; fall back to guidance keyed off the
      // two real signals rather than a fabricated Lung-RADS category.
      recommendations: Array.isArray(baseResult.recommendations) && baseResult.recommendations.length
        ? baseResult.recommendations
        : generateLungRecommendations(flaggedByModel, clinicalRiskLevel),
      requiresHumanReview: baseResult.requiresHumanReview !== false,
    };
  };

  const generateLungRecommendations = (
    flaggedByModel: boolean,
    clinicalRisk: string
  ): string[] => {
    const base = [
      'Smoking cessation support if applicable',
      'Report any new or worsening respiratory symptoms promptly'
    ];

    if (flaggedByModel) {
      return [
        'Priority radiologist review of this scan',
        'Pulmonologist consultation for clinical correlation',
        'Diagnostic imaging and tissue sampling as clinically indicated',
        ...base
      ];
    }

    if (clinicalRisk === 'high') {
      return [
        'Routine radiologist review of this scan',
        'Discuss low-dose CT screening eligibility with a clinician — the ' +
        'questionnaire indicates elevated risk regardless of this image',
        ...base
      ];
    }

    return [
      'Routine radiologist review of this scan',
      'Screening interval as advised by the treating clinician',
      ...base
    ];
  };

  const handleFileSelect = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      const allowedTypes = ['image/jpeg', 'image/jpg', 'image/png', 'image/tiff', 'image/tif', 'image/webp', 'image/avif'];
      
      if (!allowedTypes.includes(file.type)) {
        toast({
          title: "Invalid File Type",
          description: "Please select a valid medical image file",
          variant: "destructive",
        });
        return;
      }

      if (file.size > 50 * 1024 * 1024) {
        toast({
          title: "File Too Large",
          description: "Please select an image under 50MB",
          variant: "destructive",
        });
        return;
      }

      setSelectedFile(file);
      setPreviewUrl(URL.createObjectURL(file));
    }
  };

  const startAnalysis = () => {
    if (!selectedFile) {
      toast({
        title: "No Image Selected",
        description: "Please select a chest imaging file to analyze",
        variant: "destructive",
      });
      return;
    }

    setIsAnalyzing(true);
    setAnalysisProgress(0);
    setAnalysisResult(null);

    const progressInterval = setInterval(() => {
      setAnalysisProgress(prev => {
        if (prev >= 90) {
          clearInterval(progressInterval);
          return 90;
        }
        return prev + Math.random() * 15;
      });
    }, 300);

    lungAnalysisMutation.mutate({ file: selectedFile, riskFactors });
  };

  const resetAnalysis = () => {
    setSelectedFile(null);
    setPreviewUrl('');
    setAnalysisResult(null);
    setIsAnalyzing(false);
    setAnalysisProgress(0);
    setActiveTab('upload');
  };

  const getLungRadsColor = (score: number) => {
    if (score <= 2) return 'bg-green-100 text-green-800';
    if (score === 3) return 'bg-yellow-100 text-yellow-800';
    if (score === 4) return 'bg-orange-100 text-orange-800';
    return 'bg-red-100 text-red-800';
  };

  const getRiskColor = (risk: string) => {
    switch (risk) {
      case 'low': return 'bg-green-100 text-green-800';
      case 'intermediate': return 'bg-yellow-100 text-yellow-800';
      case 'high': return 'bg-red-100 text-red-800';
      default: return 'bg-gray-100 text-gray-800';
    }
  };

  return (
    <div className="space-y-6">
      <Card className="bg-[#1e40af] text-white">
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-2xl">
            <Wind className="w-6 h-6 text-white" />
            Lung Cancer Detection & Analysis
          </CardTitle>
          <CardDescription className="text-white">
            Advanced AI-powered chest imaging analysis with Lung-RADS classification
          </CardDescription>
        </CardHeader>
      </Card>

      <Tabs value={activeTab} onValueChange={setActiveTab} className="space-y-6">
        <TabsList className="grid w-full grid-cols-4">
          <TabsTrigger value="upload">Image Upload</TabsTrigger>
          <TabsTrigger value="risk-factors">Risk Assessment</TabsTrigger>
          <TabsTrigger value="analysis">Analysis</TabsTrigger>
          <TabsTrigger value="results">Results</TabsTrigger>
        </TabsList>

        <TabsContent value="upload" className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Upload className="w-5 h-5" />
                Chest Imaging Upload
              </CardTitle>
              <CardDescription>
                Upload chest X-ray, CT scan, or PET scan for lung cancer analysis
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="border-2 border-dashed border-gray-300 rounded-lg p-8 text-center">
                {previewUrl ? (
                  <div className="space-y-4">
                    <img 
                      src={previewUrl} 
                      alt="Chest imaging preview" 
                      className="max-h-64 mx-auto rounded-lg shadow-md"
                    />
                    <div className="flex justify-center gap-2">
                      <Button variant="outline" onClick={() => {
                        setSelectedFile(null);
                        setPreviewUrl('');
                      }}>
                        Remove Image
                      </Button>
                      <Button onClick={() => setActiveTab('risk-factors')}>
                        Continue to Risk Assessment
                      </Button>
                    </div>
                  </div>
                ) : (
                  <div className="space-y-4">
                    <Wind className="w-16 h-16 text-gray-400 mx-auto" />
                    <div>
                      <p className="text-lg font-medium text-gray-700">Upload Chest Imaging</p>
                      <p className="text-sm text-gray-500">
                        Chest X-rays, CT scans, or PET scans accepted
                      </p>
                    </div>
                    <div>
                      <input
                        type="file"
                        accept="image/*"
                        onChange={handleFileSelect}
                        className="hidden"
                        id="lung-image-upload"
                      />
                      <Label htmlFor="lung-image-upload">
                        <Button variant="outline" className="cursor-pointer" asChild>
                          <span>
                            <Upload className="w-4 h-4 mr-2" />
                            Select Image
                          </span>
                        </Button>
                      </Label>
                    </div>
                  </div>
                )}
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="risk-factors" className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>Patient Risk Factor Assessment</CardTitle>
              <CardDescription>
                Provide patient information to enhance analysis accuracy
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="space-y-4">
                  <div>
                    <Label>Smoking History</Label>
                    <Select 
                      value={riskFactors.smokingHistory} 
                      onValueChange={(value: any) => setRiskFactors(prev => ({...prev, smokingHistory: value}))}
                    >
                      <SelectTrigger>
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="never">Never smoker</SelectItem>
                        <SelectItem value="former">Former smoker</SelectItem>
                        <SelectItem value="current">Current smoker</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>

                  <div>
                    <Label>Pack-Years (if applicable)</Label>
                    <Input
                      type="number"
                      value={riskFactors.packYears}
                      onChange={(e) => setRiskFactors(prev => ({...prev, packYears: parseInt(e.target.value) || 0}))}
                      placeholder="0"
                    />
                  </div>

                  <div>
                    <Label>Age</Label>
                    <Input
                      type="number"
                      value={riskFactors.age}
                      onChange={(e) => setRiskFactors(prev => ({...prev, age: parseInt(e.target.value) || 50}))}
                      placeholder="50"
                    />
                  </div>
                </div>

                <div className="space-y-4">
                  <div className="flex items-center space-x-2">
                    <Checkbox
                      id="family-history"
                      checked={riskFactors.familyHistory}
                      onCheckedChange={(checked) => setRiskFactors(prev => ({...prev, familyHistory: checked as boolean}))}
                    />
                    <Label htmlFor="family-history">Family history of lung cancer</Label>
                  </div>

                  <div className="flex items-center space-x-2">
                    <Checkbox
                      id="previous-cancer"
                      checked={riskFactors.previousCancer}
                      onCheckedChange={(checked) => setRiskFactors(prev => ({...prev, previousCancer: checked as boolean}))}
                    />
                    <Label htmlFor="previous-cancer">Previous cancer diagnosis</Label>
                  </div>

                  <div className="flex items-center space-x-2">
                    <Checkbox
                      id="chronic-lung"
                      checked={riskFactors.chronicLungDisease}
                      onCheckedChange={(checked) => setRiskFactors(prev => ({...prev, chronicLungDisease: checked as boolean}))}
                    />
                    <Label htmlFor="chronic-lung">Chronic lung disease</Label>
                  </div>
                </div>
              </div>

              <div className="flex justify-between">
                <Button variant="outline" onClick={() => setActiveTab('upload')}>
                  Back to Upload
                </Button>
                <Button onClick={() => setActiveTab('analysis')} disabled={!selectedFile}>
                  Proceed to Analysis
                </Button>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="analysis" className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Target className="w-5 h-5" />
                AI Analysis in Progress
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-6">
              {!isAnalyzing ? (
                <div className="text-center space-y-4">
                  <p>Ready to analyze your chest imaging with the provided risk factors.</p>
                  <Button onClick={startAnalysis} size="lg">
                    <Zap className="w-4 h-4 mr-2" />
                    Start Lung Cancer Analysis
                  </Button>
                </div>
              ) : (
                <div className="space-y-4">
                  <div className="flex items-center justify-between">
                    <span className="text-sm font-medium">Analysis Progress</span>
                    <span className="text-sm text-gray-500">{Math.round(analysisProgress)}%</span>
                  </div>
                  <Progress value={analysisProgress} className="w-full" />
                  <div className="text-center space-y-2">
                    <Activity className="w-8 h-8 text-blue-600 mx-auto animate-pulse" />
                    <p className="text-sm text-gray-600">
                      AI is analyzing your chest imaging for lung cancer indicators...
                    </p>
                  </div>
                </div>
              )}
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="results" className="space-y-6">
          {analysisResult ? (
            <div className="space-y-6">
              {/* Main Results */}
              <Card className="bg-[#1e40af] text-white">
                <CardHeader>
                  <div className="flex items-center justify-between">
                    <CardTitle className="flex items-center gap-2">
                      <Wind className="w-5 h-5 text-white" />
                      Lung Cancer Analysis Results
                    </CardTitle>
                    <div className="flex gap-2">
                      <Badge className="bg-white text-[#1e40af] font-semibold">
                        {analysisResult?.flaggedByModel ? 'FLAGGED BY MODEL' : 'NOT FLAGGED'}
                      </Badge>
                      <Badge className="bg-white text-[#1e40af] font-semibold">
                        QUESTIONNAIRE RISK: {analysisResult?.clinicalRiskLevel?.toUpperCase()}
                      </Badge>
                    </div>
                  </div>
                  <CardDescription className="text-white">
                    Analysis Confidence: {analysisResult?.confidence ?? 'N/A'}%
                  </CardDescription>
                </CardHeader>
                <CardContent className="space-y-6 text-white">
                  {/* Two signals, deliberately not merged. The classifier saw the
                      image; the questionnaire did not. Nodule size, location,
                      density and margins used to be shown here from random
                      values — the model measures none of them. */}
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <div>
                      <h4 className="font-semibold mb-3">Image classifier</h4>
                      <div className="space-y-2 text-sm">
                        <div className="flex justify-between">
                          <span className="text-gray-300">Flagged as suspicious:</span>
                          <span className="font-semibold">
                            {analysisResult?.flaggedByModel ? 'Yes' : 'No'}
                          </span>
                        </div>
                        <div className="flex justify-between">
                          <span className="text-gray-300">Classifier confidence:</span>
                          <span className="font-semibold">
                            {analysisResult?.confidence.toFixed(1)}%
                          </span>
                        </div>
                        <p className="text-xs text-gray-300 pt-2">
                          The classifier returns a label and a probability. It does not
                          measure nodule size, location, density or margins, and it does
                          not produce a Lung-RADS category or a stage.
                        </p>
                      </div>

                      <h4 className="font-semibold mt-5 mb-3">
                        Questionnaire risk ({analysisResult?.clinicalRiskLevel})
                      </h4>
                      <ul className="space-y-1 text-sm">
                        {analysisResult?.clinicalRiskFactors.map((factor, index) => (
                          <li key={index} className="text-gray-200">• {factor}</li>
                        ))}
                      </ul>
                      <p className="text-xs text-gray-300 pt-2">
                        Calculated from your answers only, not from the image.
                      </p>
                    </div>
                    <div>
                      <h4 className="font-semibold mb-3">Recommendations</h4>
                      <ul className="space-y-2">
                        {analysisResult?.recommendations?.map((rec, index) => (
                          <li key={index} className="text-sm flex items-start gap-2">
                            <CheckCircle className="w-4 h-4 text-green-300 flex-shrink-0 mt-0.5" />
                            {rec}
                          </li>
                        ))}
                      </ul>
                    </div>
                  </div>

                  <Alert className="bg-[#1e3a8a] border-[#3b5bdb]">
                    <AlertTriangle className="h-4 w-4" />
                    <AlertDescription className="text-white">
                      <strong>Screening triage only.</strong> Blood biomarker panels
                      (CEA, CYFRA 21-1, NSE, proGRP) and TNM staging were previously
                      displayed here from randomly generated values. They require
                      laboratory testing and a full clinical workup, so they have been
                      removed. A radiologist must review this scan; a result that is
                      not flagged is not a clearance.
                    </AlertDescription>
                  </Alert>

                </CardContent>
              </Card>

              <div className="flex justify-center">
                <Button onClick={resetAnalysis} variant="outline">
                  Start New Analysis
                </Button>
              </div>
            </div>
          ) : (
            <Card>
              <CardContent className="p-8 text-center">
                <Wind className="w-16 h-16 text-gray-400 mx-auto mb-4" />
                <p className="text-gray-600">No analysis results yet. Please complete the analysis process.</p>
              </CardContent>
            </Card>
          )}
        </TabsContent>
      </Tabs>
    </div>
  );
}
